### PR TITLE
Suaoki/Mileseey P7 device support

### PR DESCRIPTION
**Pull request by f3sty**
Adds support for Suaoki/Mileseey P7 ble devices.

Suaoki P7: https://www.suaoki.com/products/p7-laser-distance-measure
Mileseey P7: https://www.mileseey.net/index.php?m=Goods&a=show&id=53

### CODE REVIEW

**Comment by lz1asl** [comment]
@f3sty the version should be available at Google Play, could you please have a look and test with your devices? 
Once again, great job!

**Comment by f3sty** [comment]
> @f3sty the version should be available at Google Play, could you please have a look and test with your devices?
> Once again, great job!

Looks good to me, thanks!
cavesurvey_p7

**Comment by f3sty** [comment]
@lz1asl This PR doesn't appear to have been merged. 
Was there a problem with it?

**Comment by lz1asl** [comment]
Will check it, thank you!

**Comment by lz1asl** [comment]
Completely my failt, thank you @f3sty for spotting it!

**Pull request merged**
